'use client';

import React from 'react';
import { DashboardLayout } from '@/components/DashboardLayout';
import { 
  Rocket, 
  Terminal, 
  Settings, 
  ChevronRight, 
  Trash2, 
  Edit2,
  Database,
  Globe,
  Clock,
  Eye,
  CheckCircle2,
  FileCode,
  Box
} from 'lucide-react';
import { motion } from 'motion/react';
import { cn } from '@/lib/utils';
import Link from 'next/link';

const pipelineDetails = [
  { label: 'ID', value: '1502' },
  { label: 'Notes', value: 'Deployment Pipeline for Magento 2 auto generated by Corefinity.' },
  { label: 'Environment', value: 'Production', isLink: true },
  { label: 'Root Web Directory', value: '/var/www_m2/example.com/', isMono: true },
  { label: 'Root Storage Directory', value: '/var/www_m2/example.com/', isMono: true },
  { label: 'Turn Nginx Container Off', value: 'False', isStatus: true, status: 'error' },
  { label: 'Enable Redis prefix change during build', value: 'False', isStatus: true, status: 'error' },
  { label: 'Deployment Pipeline', value: 'Magento 2', isHighlight: true },
  { label: 'Tag', value: '—' },
  { label: 'Use Custom Build Commands', value: 'Yes', isStatus: true, status: 'success' },
];

const history = [
  { id: '116229', name: 'Update', user: 'David Walsh', status: 'Finished', date: '2026-04-07 14:57:51' },
  { id: '116228', name: 'Update', user: 'David Walsh', status: 'Finished', date: '2026-04-07 14:49:16' },
  { id: '115641', name: 'Update', user: 'Adam Preece', status: 'Finished', date: '2026-03-31 09:49:57' },
];

export default function PipelineDetailPage() {
  return (
    <DashboardLayout>
      <nav className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-8">
        <Link href="/" className="hover:text-brand-blue">Home</Link> <ChevronRight className="w-3 h-3" />
        <Link href="/environments" className="hover:text-brand-blue">Environments</Link> <ChevronRight className="w-3 h-3" />
        <span className="text-brand-navy">Magento 2 Deployment Pipeline</span>
      </nav>

      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
        <div>
          <h1 className="text-4xl font-display font-bold text-brand-navy tracking-tight mb-2">
            Pipeline Details
          </h1>
          <p className="text-sm font-medium text-gray-400">Configuration and execution history for the Magento 2 pipeline.</p>
        </div>
        <div className="flex items-center gap-3">
           <button className="p-3 bg-white border border-gray-100 text-gray-400 hover:text-brand-error rounded-xl shadow-sm transition-all"><Trash2 className="w-5 h-5" /></button>
           <button className="flex items-center gap-2 px-6 py-3 bg-brand-orange text-white text-xs font-bold rounded-xl shadow-premium hover:bg-[#E55A1E] transition-all">
             <Edit2 className="w-4 h-4" /> Edit Pipeline
           </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        {/* Main Info */}
        <div className="lg:col-span-8 space-y-12">
           <div className="bg-white rounded-[40px] shadow-premium border border-gray-50 overflow-hidden">
              <div className="p-10 border-b border-gray-50 bg-gray-50/20 flex items-center justify-between">
                 <div className="flex items-center gap-6">
                    <div className="w-14 h-14 rounded-2xl bg-brand-navy flex items-center justify-center text-white shadow-lg">
                       <Box className="w-7 h-7" />
                    </div>
                    <div>
                       <h3 className="text-xl font-display font-bold text-brand-navy tracking-tight">Magento 2 Deployment Pipeline</h3>
                       <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">ID: 1502</p>
                    </div>
                 </div>
                 <div className="flex items-center gap-2">
                    <span className="px-3 py-1 bg-brand-success/10 text-brand-success text-[10px] font-bold rounded-full uppercase tracking-widest">Active</span>
                 </div>
              </div>
              <div className="divide-y divide-gray-50">
                 {pipelineDetails.map((item, i) => (
                   <div key={i} className="flex flex-col sm:flex-row sm:items-center py-6 px-10 group hover:bg-gray-50/50 transition-colors">
                      <span className="w-full sm:w-72 text-sm font-medium text-brand-blue">{item.label}</span>
                      <div className="flex-1 mt-1 sm:mt-0">
                         {item.isStatus ? (
                           <div className="flex items-center gap-2">
                              <div className={cn("w-2 h-2 rounded-full", item.status === 'success' ? 'bg-brand-success' : 'bg-brand-error')} />
                              <span className={cn("text-sm font-bold", item.status === 'success' ? 'text-brand-success' : 'text-brand-error')}>{item.value}</span>
                           </div>
                         ) : item.isLink ? (
                           <span className="text-sm font-bold text-brand-orange hover:underline cursor-pointer">{item.value}</span>
                         ) : item.isHighlight ? (
                           <span className="text-sm font-bold text-brand-blue">{item.value}</span>
                         ) : (
                           <span className={cn("text-sm font-bold text-brand-navy", item.isMono && "font-mono text-xs")}>{item.value}</span>
                         )}
                      </div>
                   </div>
                 ))}
              </div>

              {/* Build Commands Section */}
              <div className="p-10 bg-gray-50/50 border-t border-gray-100">
                 <div className="mb-6 flex items-center justify-between">
                    <h4 className="text-sm font-bold text-brand-navy uppercase tracking-widest">Custom Build Commands</h4>
                    <button className="text-[10px] font-bold text-brand-blue hover:underline uppercase tracking-widest">Edit Commands</button>
                 </div>
                 <div className="bg-[#0F172A] rounded-2xl p-8 font-mono text-[11px] leading-relaxed text-gray-300 border border-white/5 shadow-2xl relative group">
                    <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
                       <Terminal className="w-4 h-4 text-gray-500" />
                    </div>
                    <div className="space-y-1">
                       <p><span className="text-brand-orange mr-4">1</span> composer install --ignore-platform-reqs --no-dev --no-interaction --no-progress --prefer-dist --no-suggest</p>
                       <p><span className="text-brand-orange mr-4">2</span> php bin/magento setup:upgrade --keep-generated</p>
                       <p><span className="text-brand-orange mr-4">3</span> php bin/magento setup:di:compile</p>
                       <p><span className="text-brand-orange mr-4">4</span> composer dump-autoload --no-ansi --no-scripts --no-interaction --optimize --apcu</p>
                       <p><span className="text-brand-orange mr-4">5</span> php bin/magento setup:static-content:deploy en_GB en_US -f</p>
                    </div>
                 </div>
              </div>

              <div className="p-10 bg-gray-50/50 border-t border-gray-100">
                 <div className="mb-6 flex items-center justify-between">
                    <h4 className="text-sm font-bold text-brand-navy uppercase tracking-widest">Custom Post Build Commands</h4>
                    <button className="text-[10px] font-bold text-brand-blue hover:underline uppercase tracking-widest">Edit Commands</button>
                 </div>
                 <div className="bg-[#0F172A] rounded-2xl p-8 font-mono text-[11px] leading-relaxed text-gray-300 border border-white/5 shadow-2xl">
                    <div className="space-y-1">
                       <p><span className="text-brand-orange mr-4">1</span> php bin/magento cache:enable</p>
                       <p><span className="text-brand-orange mr-4">2</span> php bin/magento cache:flush</p>
                    </div>
                 </div>
              </div>
           </div>
        </div>

        {/* History Sidebar */}
        <div className="lg:col-span-4 space-y-8">
           <div className="bg-white rounded-[40px] p-8 shadow-card border border-gray-50">
              <h3 className="text-xs font-bold text-brand-blue uppercase tracking-widest mb-8">Execution History</h3>
              <div className="space-y-6">
                 {history.map((h, i) => (
                   <div key={i} className="flex items-center justify-between group cursor-pointer hover:translate-x-2 transition-transform">
                      <div className="flex items-center gap-4">
                         <div className="w-10 h-10 rounded-xl bg-gray-50 flex items-center justify-center text-gray-400 group-hover:bg-brand-blue/10 group-hover:text-brand-blue transition-all">
                            <Rocket className="w-5 h-5" />
                         </div>
                         <div>
                            <p className="text-sm font-bold text-brand-navy">{h.name}</p>
                            <p className="text-[10px] text-gray-400 font-bold">{h.user}</p>
                         </div>
                      </div>
                      <div className="text-right">
                         <p className="text-[10px] font-bold text-brand-success uppercase tracking-widest">{h.status}</p>
                         <p className="text-[9px] text-gray-400 font-medium">{h.date}</p>
                      </div>
                   </div>
                 ))}
                 <button className="w-full py-4 text-[10px] font-bold text-brand-blue uppercase tracking-widest hover:bg-gray-50 rounded-2xl transition-all mt-4">View All History</button>
              </div>
           </div>

           <div className="bg-brand-navy rounded-[40px] p-10 text-white shadow-premium relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-brand-blue/20 blur-[60px] rounded-full -mr-16 -mt-16" />
              <Terminal className="w-10 h-10 text-brand-orange mb-6" />
              <h3 className="text-lg font-display font-bold mb-2">Automated Pipelines</h3>
              <p className="text-[11px] text-gray-400 font-medium leading-relaxed mb-6">
                This pipeline is configured to automatically trigger on branch pushes. Ensure all environment variables are correctly mapped.
              </p>
              <div className="flex items-center gap-2 text-brand-success text-[10px] font-bold uppercase tracking-widest">
                 <CheckCircle2 className="w-4 h-4" /> Ready for deployment
              </div>
           </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
